# Quest Pack 2 (1.0) by Windyplains

strings = [

	# Quest Descriptions
	("qp2_quest_title", "Exploitable Trade Situation"),
	("qp2_shortage_of_s14_in_s13_initiation", "Through your trade contracts you've learned that a severe shortage of {s14} currently exists in the town of {s13}.  A wise trader would do well to exploit this opportunity, but time is of the essence as your competition will undoubtably do the same."),
	("qp2_surplus_of_s14_in_s13_initiation", "Through your trade contracts you've learned that an abundant surplus of {s14} currently exists in the town of {s13}.  A wise trader would do well to exploit this opportunity, but time is of the essence as your competition will undoubtably do the same."),
	("qp2_fortune_s14_for_s13_and_bring_back_s15_initiation", "By listening to the local merchants, you've learned that the regular caravan route carrying {s14} to {s13} and bringing {s15} back has been blocked by bandits.  This provides an ample opportunity for profit if you can survive the road."),
	
	# Quest - Trade Shortage
	("qp2_shortage_title", "Trade Shortage"),
	# Quest - Trade Surplus
	("qp2_surplus_title", "Trade Surplus"),
	# Quest - Fortune Favors the Bold
	("qp2_fortune_title", "Fortune Favors The Bold"),
	("qp2_fortune_1st", "first"),
	("qp2_fortune_2nd", "second"),
	("qp2_fortune_3rd", "final"),
	# Quest - A Noble Opportunity
	("qp2_opportunity_title", "A Noble Opportunity"),
	# Quest - Discount Enterprise
	("qp2_discount_title", "Discount Enterprise"),
	
	# Trade Rival Debug Display
	("qp2_trd_label_relation_factions", "Relation With Kingdoms"),
	("qp2_trd_label_relation_rivals",   "Relation With Rivals"),
	("qp2_trd_label_last_quest",        "Last Quest Attempted:"),
	("qp2_trd_label_current_quest",     "Current Quest:"),
	("qp2_trd_label_kingdom_s31_relation_reg31",  "{s31} {reg31}"),
	#("qp2_trd_label_relation_rivals",   "Relation With Rivals"),
	("qp2_trd_label_cur_quest_stage",   "Stage {reg31} with a {reg32}% chance of advancing to stage {reg33}."),
	("qp2_trd_label_level",             "Proficiency {reg31} / Level {reg32}"),
	("qp2_trd_label_done",              "Done"),
	("qp2_trd_label_s31",               "{s31}"),
	("qp2_trd_label_reg31",             "{reg31}"),
	("qp2_trd_label_last_quest_s31",    "Quest - {s31}"),
	("qp2_trd_last_quest_s31_winner",   "Completed first by {s31}"),
	("qp2_trd_button_next",             "Next"),
	("qp2_trd_button_prev",             "Prev"),
	("qp2_trd_label_useful_stats",      "Merchant Information"),
	
	# Rival Slot Descriptions
	("qp2_rival_data_unused", "unused"),
	("qp2_rival_slot_200", "proficiency"),
	("qp2_rival_slot_201", "status"),
	("qp2_rival_slot_202", "trade skill"),
	("qp2_rival_slot_203", "location"),
	("qp2_rival_slot_204", "x-loc"),
	("qp2_rival_slot_205", "y-loc"),
	("qp2_rival_slot_206", "destination"),
	("qp2_rival_slot_207", "current wealth"),
	("qp2_rival_slot_208", "accumulated wealth"),
	("qp2_rival_slot_209", "home region"),
	("qp2_rival_slot_210", "relation with player"),
	("qp2_rival_slot_211", "relation with rival 1"),
	("qp2_rival_slot_212", "relation with rival 2"),
	("qp2_rival_slot_213", "relation with rival 3"),
	("qp2_rival_slot_214", "relation with rival 4"),
	("qp2_rival_slot_215", "relation with rival 5"),
	("qp2_rival_slot_216", "relation with rival 6"),
	("qp2_rival_slot_217", "relation with rival 7"),
	("qp2_rival_slot_218", "relation with rival 8"),
	("qp2_rival_slot_219", "relation with rival 9"),
	("qp2_rival_slot_220", "relation with rival 10"),
	("qp2_rival_slot_221", "relation with rival 11"),
	("qp2_rival_slot_222", "relation with rival 12"),
	("qp2_rival_slot_223", "relation with rival 13"),
	("qp2_rival_slot_224", "relation with rival 14"),
	("qp2_rival_slot_225", "relation with rival 15"),
	("qp2_rival_slot_226", "relation with player faction"),
	("qp2_rival_slot_227", "relation with kingdom 1"),
	("qp2_rival_slot_228", "relation with kingdom 2"),
	("qp2_rival_slot_229", "relation with kingdom 3"),
	("qp2_rival_slot_230", "relation with kingdom 4"),
	("qp2_rival_slot_231", "relation with kingdom 5"),
	("qp2_rival_slot_232", "relation with kingdom 6"),
	("qp2_rival_slot_233", "relation with kingdom 7"),
	("qp2_rival_slot_234", "relation with kingdom 8"),
	("qp2_rival_slot_235", "relation with kingdom 9"),
	("qp2_rival_slot_236", "relation with kingdom 10"),
	("qp2_rival_slot_237", "relation with kingdom 11"),
	("qp2_rival_slot_238", "relation with kingdom 12"),
	("qp2_rival_slot_239", "relation with kingdom 13"),
	("qp2_rival_slot_240", "relation with kingdom 14"),
	("qp2_rival_slot_241", "relation with kingdom 15"),
	("qp2_rival_slot_242", "relation with kingdom 16"),
	("qp2_rival_slot_243", "last quest attempted"),
	("qp2_rival_slot_244", "last quest winner"),
	("qp2_rival_slot_245", "last quest destination"),
	("qp2_rival_slot_246", "last quest focus"),
	("qp2_rival_slot_247", "last quest commentary"),
	("qp2_rival_slot_248", "destination lockout"),
	("qp2_rival_slot_249", "unused"),
	("qp2_rival_slot_250", "unused"),
	("qp2_rival_slot_251", "unused"),
	("qp2_rival_slot_252", "unused"),
	("qp2_rival_slot_253", "unused"),
	("qp2_rival_slot_254", "unused"),
	("qp2_rival_slot_255", "unused"),
	("qp2_rival_slot_256", "unused"),
	("qp2_rival_slot_257", "unused"),
	("qp2_rival_slot_258", "unused"),
	("qp2_rival_slot_259", "unused"),
	("qp2_rival_slot_260", "unused"),
	("qp2_rival_slot_261", "unused"),
	("qp2_rival_slot_262", "unused"),
	("qp2_rival_slot_263", "unused"),
	("qp2_rival_slot_264", "unused"),
	("qp2_rival_slot_265", "unused"),
	("qp2_rival_slot_266", "unused"),
	("qp2_rival_slot_267", "unused"),
	("qp2_rival_slot_268", "unused"),
	("qp2_rival_slot_269", "unused"),
	("qp2_rival_slot_270", "unused"),
	("qp2_rival_slot_271", "unused"),
	("qp2_rival_slot_272", "unused"),
	("qp2_rival_slot_273", "unused"),
	("qp2_rival_slot_274", "unused"),
	("qp2_rival_slot_275", "unused"),
	("qp2_rival_slot_276", "unused"),
	("qp2_rival_slot_277", "unused"),
	("qp2_rival_slot_278", "unused"),
	("qp2_rival_slot_279", "unused"),
	("qp2_rival_slot_280", "unused"),
	("qp2_rival_slot_281", "unused"),
	("qp2_rival_slot_282", "unused"),
	("qp2_rival_slot_283", "unused"),
	("qp2_rival_slot_284", "unused"),
	("qp2_rival_slot_285", "unused"),
	("qp2_rival_slot_286", "unused"),
	("qp2_rival_slot_287", "unused"),
	("qp2_rival_slot_288", "unused"),
	("qp2_rival_slot_289", "unused"),
	("qp2_rival_slot_290", "unused"),
	("qp2_rival_slot_291", "unused"),
	("qp2_rival_slot_292", "unused"),
	("qp2_rival_slot_293", "unused"),
	("qp2_rival_slot_294", "unused"),
	("qp2_rival_slot_295", "unused"),
	("qp2_rival_slot_296", "unused"),
	("qp2_rival_slot_297", "unused"),
	("qp2_rival_slot_298", "unused"),
	("qp2_rival_slot_299", "unused"),
	("qp2_rival_slot_300", "trade shortage quest status"),
	("qp2_rival_slot_301", "trade shortage quest stage"),
	("qp2_rival_slot_302", "trade shortage trigger chance"),
	("qp2_rival_slot_303", "unused"),
	("qp2_rival_slot_304", "unused"),
	("qp2_rival_slot_305", "unused"),
	("qp2_rival_slot_306", "unused"),
	("qp2_rival_slot_307", "unused"),
	("qp2_rival_slot_308", "unused"),
	("qp2_rival_slot_309", "unused"),
	("qp2_rival_slot_310", "trade surplus quest status"),
	("qp2_rival_slot_311", "trade surplus quest stage"),
	("qp2_rival_slot_312", "trade surplus trigger chance"),
	("qp2_rival_slot_313", "unused"),
	("qp2_rival_slot_314", "unused"),
	("qp2_rival_slot_315", "unused"),
	("qp2_rival_slot_316", "unused"),
	("qp2_rival_slot_317", "unused"),
	("qp2_rival_slot_318", "unused"),
	("qp2_rival_slot_319", "unused"),
	("qp2_rival_slot_320", "fortune favors quest status"),
	("qp2_rival_slot_321", "fortune favors quest stage"),
	("qp2_rival_slot_322", "fortune favors cycle count"),
	("qp2_rival_slot_323", "fortune favors trigger chance"),
	("qp2_rival_slot_324", "unused"),
	("qp2_rival_slot_325", "unused"),
	("qp2_rival_slot_326", "unused"),
	("qp2_rival_slot_327", "unused"),
	("qp2_rival_slot_328", "unused"),
	("qp2_rival_slot_329", "unused"),
]

from util_common import *

def modmerge_strings(orig_strings):
    # add remaining strings
    from util_common import add_objects
    num_appended, num_replaced, num_ignored = add_objects(orig_strings, strings)
    #print num_appended, num_replaced, num_ignored
	
	
# Used by modmerger framework version >= 200 to merge stuff
# This function will be looked for and called by modmerger if this mod is active
# Do not rename the function, though you can insert your own merging calls where indicated
def modmerge(var_set):
    try:
        var_name_1 = "strings"
        orig_strings = var_set[var_name_1]
        modmerge_strings(orig_strings)
    except KeyError:
        errstring = "Variable set does not contain expected variable: \"%s\"." % var_name_1
        raise ValueError(errstring)